<?php
$dir_plantilla = "../../plantillas/gentelella-master/";
?>

<!-- Bootstrap -->
<link href="<?php echo $dir_plantilla; ?>vendors/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet">
<!-- Font Awesome -->
<link href="<?php echo $dir_plantilla; ?>vendors/font-awesome/css/font-awesome.min.css" rel="stylesheet">
<!-- NProgress -->
<link href="<?php echo $dir_plantilla; ?>vendors/nprogress/nprogress.css" rel="stylesheet">
<link rel="stylesheet" href="//code.jquery.com/ui/1.12.0/themes/base/jquery-ui.css">
