<?php
$dir_plantilla = "../../plantillas/gentelella-master/";
?>
<!-- JQuery -->
<?= Tag::js('jquery/jquery-1.12.4'); ?>
<!-- Bootstrap -->
<script src="<?php echo $dir_plantilla; ?>vendors/bootstrap/dist/js/bootstrap.min.js"></script>
<!-- FastClick -->
<script src="<?php echo $dir_plantilla; ?>vendors/fastclick/lib/fastclick.js"></script>
<!-- NProgress -->
<script src="<?php echo $dir_plantilla; ?>vendors/nprogress/nprogress.js"></script>
<script src="<?php echo $dir_plantilla; ?>vendors/fastclick/lib/fastclick.js"></script>
<!-- NProgress -->
<script src="<?php echo $dir_plantilla; ?>vendors/nprogress/nprogress.js"></script>
